### ISSUE TITLE
connection reset by peer?

### ISSUE THREAD

**Issue by luckypoem** [txthinking/ipio#4]
hi.

yudeMacBook-Air:~ brite$ sudo ./ipio_darwin_amd64 tun2brookserver -s my-vps-public-ip:5080 -p mypassword
Password:

Running, must exit by Ctrl+C or send INT/TERM signal to me
2020/10/08 19:03:40 classichandler.go:139: read tcp 192.168.1.100:57211->my-vps-public-ip:5080: read: connection reset by peer
2020/10/08 19:03:40 classichandler.go:139: read tcp 192.168.1.100:57209->my-vps-public-ip:5080: read: connection reset by peer

怎么解决？

**Comment by txthinking** [comment]
Test first
https://github.com/txthinking/brook/issues/575

**Comment by luckypoem** [comment]
hi.
my-vps-public-ip:5080没被封锁，我可以用brookserver 成功翻墙。（socks proxy)

**Comment by txthinking** [comment]
Which version about ipio and brook?

**Comment by luckypoem** [comment]
oh,i see.
本地机器的ipio 版本是20201111，服务器上的brook的版本是20190601，我在服务器另外下载了brook_linux_amd64_v20200909，本地的ipio 搭配这个brook_linux_amd64_v20200909就没有问题了，可以构建一个vpn,成功的翻墙了。

**Comment by txthinking** [comment]
ipio requires brook >= v20200901

**Comment by luckypoem** [comment]
你这是VPN,对吗？不过我运行sudo lsof -I:53 没有显示内容，这个ipio没有监听53端口，那么它监听的是哪个端口？

**Comment by luckypoem** [comment]
我看了我的mac机器的dns服务器地址是我的isp的dns服务器地址，怎么用你这个vpn程序翻墙时，竟然没有遇到dns污染问题，为什么？可以解释一下吗？
为了安全起见，我运行了：
sudo networksetup -setdnsservers "Wi-Fi" 127.0.0.1 ，把本地机器的dns服务器地址改为了127.0.0.1 ，然后在本地机器运行一个dns proxy，这样就能安心的用你这个vpn程序翻墙了

**Comment by txthinking** [comment]
正常情况下 ipio 会修改系统dns为8.8.8.8

**Comment by luckypoem** [comment]
hi.
我记得以前那个brook的vpn模式，本地的brook是 监听53端口的，能否在ipio的新版中，把ipio也改为监听53端口？我觉得这样比较安全。

**Comment by txthinking** [comment]
以前的brook vpn 命令会内建dns server, 但是这个ipio就比较纯粹了, 他关心流经他网卡的流量,
而不关心TCP/UDP之上的具体协议.
所以如果你设置了8.8.8.8 dns, 并且没有bypass调8.8.8.8的话, 那么dns就会走ipio. ,
如果ipio是tun2brookserver和你单独再用 $ brook dns 建一个加密dns server就一样

**Comment by luckypoem** [comment]
hi。

首先谢谢你开发了这么好用的程序。只是我挂了该vpn后，访问github.com网站，却打不开。不知道为什么？

**Comment by txthinking** [comment]
我抽空做一系列YouTube视频

**Comment by txthinking** [comment]
https://github.com/txthinking/ipio/issues/11

**Comment by txthinking** [comment]
v20210401. and document or how it works, follow:
Blog: https://talks.txthinking.com
Youtube: https://www.youtube.com/playlist?list=PLwDQR8zI95UoH5-8T4COTxwATlABbUFI5

When I have time

**Comment by luckypoem** [comment]
好久未用ipio翻墙了，今天用了之后，虽然终端里显示：running,
但就是翻不了墙，怪事。这个ipio被破解了吗？你那里还能用它翻墙吗

**Comment by luckypoem** [comment]
哦，原来是我电脑的可用磁盘太小了造成的。清理磁盘空间后，问题即可解决。
