### ISSUE TITLE
is ipio needed to run a VPN?

### ISSUE THREAD

**Issue by godbout** [txthinking/ipio#8]
i'm sure i don't grasp fully what i'm doing. i'm able to connect to a brook server, and a dns leak test shows that all is good. connection works fine. so i'm wondering what's the use of ipio? there's no much doc and i'm not an expert so probably i'm completely out of my mind, sorry :D is just going through a brook server not enough?

thanks!

**Comment by txthinking** [comment]
good suggestion.

TODO: Doc to detail how ipio work

**Comment by txthinking** [comment]
https://github.com/txthinking/ipio/issues/11

**Comment by godbout** [comment]
great, thanks. looking forward to try that once i can cross the borders. should be happening soon 🤞️

**Comment by txthinking** [comment]
v20210401. and document or how it works, follow:
Blog: https://talks.txthinking.com
Youtube: https://www.youtube.com/playlist?list=PLwDQR8zI95UoH5-8T4COTxwATlABbUFI5

When I have time
