### ISSUE TITLE
[Feature Request] Custom interface name

### ISSUE THREAD

**Issue by Handsome1080P** [txthinking/ipio#9]
Can add custom interface name function?Cuz my out interface name is "Out1".So I got this error log below:

> inet address is expected rather than "out1".

**Comment by txthinking** [comment]
good suggestion.

TODO: custom interface name

**Comment by txthinking** [comment]
https://github.com/txthinking/ipio/issues/11

**Comment by txthinking** [comment]
v20210401 --doNotChangeAnything
